# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.1.0
_src_path: gh:epics-containers/services-template-helm
beamline: bl01t
cluster_name: k8s-b01-1
cluster_namespace: b01-1-beamline
cluster_type: dls_dedicated
description: beamline bl01t IOC Instances and Services
git_platform: github.com
github_org: marcelldls
logging_url: https://graylog2.diamond.ac.uk/search?rangetype=relative&fields=message%2Csource&width=1489&highlightMessage=&relative=172800&q=pod_name%3A{service_name}*
repo_uri: git@github.com:marcelldls/bl01t.git
type: beamline
