# shared values for all services

global:
  beamline: 
  enabled: true

# ioc-instance:
#   resources:
#     limits:
#       cpu: 500m
#       memory: 1Gi
#     requests:
#       cpu: 100m
#       memory: 128Mi